language: php

php:
  - 7.3
  - nightly

install:
  composer install

script:
  - |
    cd $TRAVIS_BUILD_DIR/tools && php build.php pages static
    
    if([ $TRAVIS_PHP_VERSION == "7.3" ] && [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ])
    then
      cd $TRAVIS_BUILD_DIR/tools && php uploadToS3.php
      echo "Deployed to S3"

      # deploy to ipfs via infura
      # sadly only files without spaces for now
      # TODO: FIX THIS NOT WORKING FOR FILES WITH SPACES
      FILES=$(find * -type f | grep -v ' ' | sed -e 's/ /\\ /g' | awk -v q="'" '{print " -F " q "file=@" $0 ";filename=" $0 q}')
      //FILES=$(find * -type f | sed -e 's/ /\\ /g' | awk -v q="'" '{print " -F " q "file=" $0 ";filename=" $0 q}')
      curl "https://ipfs.infura.io:5001/api/v0/add?pin=true&recursive=true&wrap-with-directory=true" -X POST -H "Content-Type: multipart/form-data" $FILES
      echo "Deployed to IPFS via Infura"
    fi
