language: php

php:
  - 7.3
  - nightly

install:
  composer install

script:
  - |
    cd $TRAVIS_BUILD_DIR/tools && php build.php pages static
    
    if([ $TRAVIS_PHP_VERSION == "7.3" ] && [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ])
    then
      cd $TRAVIS_BUILD_DIR/tools && php uploadToS3.php
      echo "Deployed to S3"

      # deploy to ipfs via infura
      FILES=$(find * | awk '{print "-F \"file=@" $1 ";filename=" $1 "\""}')
      curl "https://ipfs.infura.io:5001/api/v0/add?pin=true&recursive=true&wrap-with-directory=true" -X POST -H "Content-Type: multipart/form-data" $FILES
      echo "Deployed to IPFS via Infura"
    fi
