language: php

php:
  - 7.3
  - nightly

install:
  composer install

script:
  - |
    cd tools && php build.php pages static
    
    if([ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ])
    then
      //cd tools && php uploadToS3.php key=$AWSACCESSKEY secret=$AWSSECRETKEY
    fi