# AWS IAM JSON:
# {
#    "Statement": [
#        {
#            "Action": "s3:*",
#            "Resource": [
#                "arn:aws:s3:::craig.mayhew.io",
#                "arn:aws:s3:::craig.mayhew.io/*"
#            ],
#            "Effect": "Allow"
#        },
#        {
#            "Action": "cloudfront:CreateInvalidation",
#            "Resource": [
#                "arn:aws:cloudfront::ACCOUNTID:distribution/DISTRIBUTIONID"
#            ],
#            "Effect": "Allow"
#        },
#        {
#            "Effect": "Allow",
#            "Action": [
#                "cloudfront:ListDistributions"
#            ],
#            "Resource": "*"
#        },{
#            "Effect": "Allow",
#            "Action": [
#                "route53:ChangeResourceRecordSets",
#                "route53:ListResourceRecordSets"
#            ],
#            "Resource": "arn:aws:route53:::hostedzone/HOSTNAME"
#        },
#        {
#            "Effect": "Allow",
#            "Action": [
#                "route53:GetChange"
#            ],
#            "Resource": "arn:aws:route53:::change/*"
#        },
#        {
#            "Effect": "Allow",
#            "Action": "route53:ListHostedZonesByName",
#            "Resource": "*"
#        }
#    ]
#}

language: php

php:
  - 7.4
  - nightly

before_install:
  - sudo apt-get update -y
  - sudo apt-get install curl -y
  - sudo apt-get install golang-go -y
  - wget https://dist.ipfs.io/go-ipfs/v0.4.23/go-ipfs_v0.4.23_linux-amd64.tar.gz
  - tar xvfz go-ipfs_v0.4.23_linux-amd64.tar.gz
  - sudo mv go-ipfs/ipfs /usr/local/bin/ipfs
  - sudo rm -rf go-ipfs/

install:
  - composer install

script:
  - |
    cd $TRAVIS_BUILD_DIR/tools && php build.php pages static
    
    if([ $TRAVIS_PHP_VERSION == "7.4" ] && [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ])
    then
      cd $TRAVIS_BUILD_DIR/tools && php uploadToS3.php
      echo "Deployed to S3"
    fi
